# Generated by Django 4.0.5 on 2022-06-17 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='site_contact',
        ),
    ]
