# Generated by Django 4.0.5 on 2022-06-17 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_remove_infoagent_facebook_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialagent',
            name='social_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_agent_social_agent', to='Customers.customer'),
        ),
    ]
