# Generated by Django 4.0.5 on 2022-06-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_number',
            field=models.CharField(default=915, max_length=150),
            preserve_default=False,
        ),
    ]
