# Generated by Django 4.0.5 on 2022-06-18 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0003_city_alter_house_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city_houses', to='House.city'),
            preserve_default=False,
        ),
    ]
