# Generated by Django 4.0.5 on 2022-06-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0004_house_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
